services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: 'letsellify-logistics-postgres'
    environment:
      - 'POSTGRES_DB=logistics_db'
      - 'POSTGRES_PASSWORD=KfiwSDrL3VPP8s15'
      - 'POSTGRES_USER=letsellify'
    ports:
      - '5444:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
#      - './src/main/resources/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql'

  axonserver:
    image: 'axoniq/axonserver:latest'
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      - '8024:8024'
      - '8124:8124'
    volumes:
      - 'axon_data:/data'
      - 'axon_events:/events'

  redis:
    image: 'redis:7-alpine'
    container_name: 'logistics_redis'
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    command: ["redis-server", "--appendonly", "yes"]


# Uncomment this to run entire app packed with all it services
#  app:
#    build:
#      context: '.'
#      dockerfile: 'Dockerfile'
#    container_name: 'letsellify-logistics-backend'
#    ports:
#      - "8181:8080"
#    env_file:
#      - .env
#    depends_on:
#      - 'postgres'
#      - 'axonserver'
#      - 'redis'
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -f http://localhost:8181/actuator/health || exit 1" ]
#      interval: '30s'
#      timeout: '10s'
#      retries: 5
#

volumes:
  pgdata:
  axon_data:
  axon_events:
  redis_data:
