# application name
spring.application.name=logistics

# admin properties
logistics.admin.name=${ADMIN_NAME}
logistics.admin.email=${ADMIN_EMAIL}
logistics.admin.password=${ADMIN_PASSWORD}


# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Enable Spring caching with Redis
spring.cache.type=redis

# Cache entry expiration time (1 day in milliseconds)
spring.cache.redis.time-to-live=86400000

# Redis connection settings
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000


# flyway configurations
spring.flyway.enabled=false


spring.datasource.url=jdbc:postgresql://postgres:5432/logistics_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.pool-name=logisticsHikariCP
spring.datasource.hikari.max-lifetime=1000000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# Maximum file size per upload (e.g., 5MB)
spring.servlet.multipart.max-file-size=5MB

# Maximum total request size (if multiple files are uploaded together, e.g., 20MB)
spring.servlet.multipart.max-request-size=20MB


# enable virtual threads automatically for entire application
spring.threads.virtual.enabled=true


# Mail server configuration
spring.mail.host=smtp.mailgun.org
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
#spring.mail.protocol=smtp

# Optional default properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

axon.axonserver.servers=axonserver:8124

# security keys path
rsa.access-token.private-key=classpath:certs/access_token_private.pem
rsa.access-token.public-key=classpath:certs/access_token_public.pem
rsa.refresh-token.private-key=classpath:certs/refresh_token_private.pem
rsa.refresh-token.public-key=classpath:certs/refresh_token_public.pem

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_BASE_URI}/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Facebook OAuth2 Client
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.client-name=Facebook
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email
spring.security.oauth2.client.provider.facebook.user-name-attribute=id


# Paystack configuration
paystack.base-url=${PAYSTACK_BASE_URL}
paystack.public-key=${PAYSTACK_PUBLIC_KEY}
paystack.secret-key=${PAYSTACK_SECRET_KEY}
paystack.payment-endpoint=${PAYSTACK_PAYMENT_ENDPOINT}
paystack.allowed-ips=${PAYSTACK_ALLOWED_IPS}

# S3 configuration
aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.s3.region=us-east-1
aws.s3.access-key=${AWS_ACCESS_KEY}
aws.s3.secret-key=${AWS_SECRET_KEY}
aws.s3.presigned-url-expiration=3600

system.account.id=${SYSTEM_ACCOUNT_ID}

spring.devtools.restart.enabled=false


state-lga.json-file-path=classpath:data/nigerian-states.json


