# application name
spring.application.name=logistics

# flyway configurations
spring.flyway.enabled=false


# Mail server configuration
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp

# Optional default properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# security keys path
rsa.access-token.private-key=classpath:certs/access_token_private.pem
rsa.access-token.public-key=classpath:certs/access_token_public.pem
rsa.refresh-token.private-key=classpath:certs/refresh_token_private.pem
rsa.refresh-token.public-key=classpath:certs/refresh_token_public.pem


# Paystack configuration
paystack.base-url=${PAYSTACK_BASE_URL}
paystack.public-key=${PAYSTACK_PUBLIC_KEY}
paystack.secret-key=${PAYSTACK_SECRET_KEY}
paystack.payment-endpoint=${PAYSTACK_PAYMENT_ENDPOINT}

